### ISSUE TITLE
Register user

### ISSUE THREAD

**Issue by enbermudas** [questocat/laravel-referral#1]
How can i register an user and fill the ``referred_by`` field ?

**Comment by questocat** [comment]
You don't need to care about this, I used model event  "creating" to auto fill the referred_by field. 
See: https://github.com/questocat/laravel-referral/blob/master/src/Traits/UserReferral.php#L33

**Comment by questocat** [comment]
> How can i register an user and fill the `referred_by` field ?

**Comment by voocx** [comment]
> How can i register an user and fill the `referred_by` field ?
You don't need to care about this, I used model events "creating" to auto fill the referred_by field.
See: https://github.com/questocat/laravel-referral/blob/master/src/Traits/UserReferral.php#L33
